### ISSUE TITLE
Update README to reflect v2

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/language-primero#15]
There are a number of outdated references to the primero v1 API on the README. Please update this to reflect the new version of the adaptor.

The `v1` branch has a README also, and that will continue to have `v1` documentation. The README on `master` should be on `v2`.

**Comment by aleksa-krolls** [comment]
@lakhassane Still no mention of `v2` on the README page: https://github.com/OpenFn/language-primero
It says `v1` is available on a different branch... but then we need to be explicit that this documentation is for `v2`. 

Then the related Github page does not reflect any of this information: https://openfn.github.io/language-primero/

**Comment by aleksa-krolls** [comment]
@lakhassane Github page is still inconsistent with README: https://github.com/OpenFn/language-primero

It says `Adaptor for Primero v2.0 coming soon!`

**Comment by taylordowns2000** [comment]
`./node_modules/.bin/jsdoc --readme ./README.md ./lib -d docs` did the trick... on these adaptor sites we need to build the docs manually.
