### ISSUE TITLE
Primero support for basic auth credential

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/language-primero#18]
## Background
For typical Primero API users, they'll need to follow the standard authentication method that generates a JWT token. 

However, for OpenFn - Primero is planning to configure a special API user with special system roles & permissions. This user is apparently configured in such a way where we can only use `basic authentication`(UN + PW)  and no need to generate a token. 
https://github.com/primeroIMS/primero/blob/development_v2/app/controllers/api/v2/docs/tokens/post.md

## Request
Is it possible to maintain 2 authentication methods for 1 adaptor? For OpenFn implementations, we will want to use the `basic auth` approach... but there might be other folks who want to talk advantage of our Primero adaptor and won't have this special user configured (and need to use the standard JWT auth approach). 

**Note this applies to Primero `v2` only**

## state
See LP for `Primero Thailand Demo API User (Open Function)` to test the basic auth approach cc @ritazagoni

**Comment by taylordowns2000** [comment]
@lakhassane , what about something like this:
![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/695b7e02-84e8-4e7c-9e43-5ee92c4ff013)

**Comment by taylordowns2000** [comment]
here's a proposal:
```js
function generateAuthString(state) {
  const { auth, configuration } = state;
  if (state.configuration.jwt) {
    return `Bearer ${token}`;
  }

  const { username, password } = configuration;
  return `${username}:${password}`;
}
```

then for EVERY function:
```js
export function getCases(query, callback) {
  return state => {
    const { url } = state.configuration;
    const { token } = state.auth;

    const params = {
      method: 'GET',
      url: `${url}/api/v2/cases`,
      headers: {
        Authorization: generateAuthString(state),
      },
      qs: query,
    };

    return new Promise((resolve, reject) => { ...
```

**Comment by aleksa-krolls** [comment]
@lakhassane @taylordowns2000 To implement this, anything we need to know? 
Here's a job on prod linked to a basic auth-enabled credential you can test with: https://www.openfn.org/projects/p5kaap/jobs/jyzqmq

**Comment by aleksa-krolls** [comment]
@lakhassane @taylordowns2000 please see my question above

**Comment by lakhassane** [comment]
Not really @aleksa-krolls We've added a new credential field (`basicAuth`) for any primero credential. So for any job that would want to use the latest `language-primero` version with the basic auth-enabled you will have to check that field, otherwise ignore it to stay with the `jwt token`
