### ISSUE TITLE
upsertCases() based on array of Id parameters

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/language-primero#2]
https://github.com/OpenFn/language-primero/blob/5ff0dddec0b6c27085ff654f9591dd1dfda4f2ab/src/Adaptor.js#L243

Primero wants to **upsert cases _based on an array of Ids_** (`oscar_number`, `case_id`), rather than a single parameter External Id. 

Alberto has confirmed it is possible to filter search parameters using "or" logic if we change the value type to `=or_op||` and use`[or]` (e.g., `scope[or][oscar_number]`). 

For example, we can GET cases using: 
`/api/cases?remote=true&scope[or][oscar_number]=or_op||23C1P15MBWYBWDG2WYRG08VCFR&scope[or][case_id]=or_op||245009bf-b251-477d-9ddc-ca32e818e21f`

He will update the API docs later today accordingly, but can we modify the `upsertCases()` to evaluate an array of Ids?

**Comment by taylordowns2000** [comment]
@aleksa-krolls , the last update I see on the google doc "API Docs" is from 13 days ago. Would you paste in a new link to make sure I'm up to speed?
