### ISSUE TITLE
`record_id` should not be sent in  request body for `upsertCase`

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/language-primero#28]
## Request
In the adaptor for `Primero API v2` we are using the Primero `record_id` as `externalId` to perform an `upsertCase` (where we send a `GET` request to Primero, and then `POST` or `PUT`/`PATCH` depending on if a case exists). Currently when we write this job expression, we are also currently including `record_id` in the request body, as part of `data` or the HTTP request body. 

We should continue using `record_id` as `externalId` in order to GET case records, however Primero has asked that we should NOT include `record_id` it in the HTTP request body when performing a `POST` or `PATCH` for cases.

See from Primero devs for reference:

> `record_id` is not a recognized field on the cases API. When you call `upsertCase()` in the Primero language pack, you can try to pop the `record_id` field off the data object in order to perform your GET query, then perform a POST/PATCH without it. 

## Expression example
See the Thailand `upsertCases` job where ideally L342 could be removed from the request body when sending POST/PATCH requests to create or update cases. 
https://github.com/OpenFn/primero-thailand/blob/master/jobs/1b-upsertCases.js#L342

## To test
For HIS login see `LP Thailand MOPH HIS webservice (UNICEF)`
For Primero login see `LP Primero Staging Thailand`

See example state [here](https://github.com/OpenFn/primero-thailand/blob/master/sampleData/state_HISpersonEndpoint14April.json)

You can re-run [this job](https://www.openfn.org/projects/p5kaap/runs/rwa8bak7) that will trigger the Primero upsert job.

**Comment by aleksa-krolls** [comment]
@ritazagoni can you please update the `To test` section to give the team a concrete example to be working with. Thanks!

**Comment by ritazagoni** [comment]
@aleksa-krolls updated!

**Comment by taylordowns2000** [comment]
This looks all good, @ritazagoni : https://www.openfn.org/projects/p5kaap/runs/r6g7wjka

Can you please confirm?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 when the client tested, they encountered the issue 'Invalid Record JSON'. 
https://www.openfn.org/projects/p5kaap/runs/r7xnpb54

Can you please take a look? Wondering if we need to remove `record_id` on L342 in this Thailand job because it looks like we're still sending it in the message body here: https://github.com/OpenFn/primero-thailand/blob/master/jobs/1b-upsertCases.js#L342
cc @ritazagoni

**Comment by taylordowns2000** [comment]
@ritazagoni , @aleksa-krolls , Primero gets a gold star for these error messages!!! Looks like this _is_ actually closed, but it looks like we should open a new issue! Can you do so once we identify the change needed?

When `record_id` is included, you'll see them tell us about it in the 422, like [this](https://www.openfn.org/projects/p5kaap/runs/rzdp8pgn):

```js
  "statusCode": 422,
  "body": {
    "errors": [
      {
        "status": 422,
        "resource": "/api/v2/cases/5c22472e-bd78-409a-a992-550a9cf66177",
        "detail": [
          "/record_id"
        ],
        "message": "Invalid Record JSON"
      }
    ]
  },
```

When `record_id` isn't the problem, you'll see them tell us about _other stuff_, like [the run you've shared above](https://www.openfn.org/projects/p5kaap/runs/r7xnpb54):

```json
  "statusCode": 422,
  "body": {
    "errors": [
      {
        "status": 422,
        "resource": "/api/v2/cases/b432853c-4f36-4979-9fd1-58f74f85ba67",
        "detail": [
          "/new_pregnancy/0/unique_id"
        ],
        "message": "Invalid Record JSON"
      }
    ]
  },
```
