### ISSUE TITLE
updateReferrals v2

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/language-primero#31]
## Background
See https://github.com/OpenFn/primero-progres/issues/30 for the issue that will need this function. 

## Request
For upcoming Primero changes, Progres will send us a decision about whether a referral is accepted rejected. We will need to update the referral with this decision. 

Please create new helper function for Primero v2: 
`updateReferrals(...)` 
`PATCH /api/v2/cases/:id/referrals/:referral_id`

**Fyi, not 100% sure if `/cases/:id` refers to `case_id` OR `record_id`** (these are 2 different uuids available for a case). If that's the case, would we need to use `getCases(...)` to find the `record_id` using the `case_id` provided? (Note: in many use cases, we only have the `case_id` available to us. 

## state
See LP for `Primero Gambella open_function API user`
You can use this case that has related referrals to test: 
 ```
 "case_id": "f59e880e-d58f-4b68-ba6e-e0616a49aefd",
 "record_id": "406b539a-e662-425e-810b-47e4fa7da496" (sometimes referred to as "id" in primero docs)
"id": "4c58d02f-3182-4006-b2fe-96aa797f5ee7" (referral id)
 ```
Sample payload HTTP Rrequest body from Quoin you can try to test updating the referral status which is currently set to `in_progress`: 
```
{ 
    "data": {
      "status": "accepted",
      "id": "4c58d02f-3182-4006-b2fe-96aa797f5ee7",
      "type": "Referral",
      "record_id": "406b539a-e662-425e-810b-47e4fa7da496",
      "record_type": "case"
   }
}
```

## API Docs
Referrals endpoint: https://github.com/primeroIMS/primero/blob/905c3d51d9ad6e71f06e6d65321b3a8e0cf14e94/app/controllers/api/v2/docs/referrals/get.md

General docs: https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api/v2/docs

**Comment by lakhassane** [comment]
@aleksa-krolls are we sure primero allows to update referrals. Can't find a right method (patch, put) and the post wouldn't work for it.

@taylordowns2000 do you know/remember ever seeing or worked on updating a referral via API?

link: https://github.com/primeroIMS/primero/tree/905c3d51d9ad6e71f06e6d65321b3a8e0cf14e94/app/controllers/api/v2/docs/referrals/id
<img width="642" alt="Screen Shot 2021-09-28 at 17 09 24" src="https://user-images.githubusercontent.com/8411231/135133539-768620ac-4548-44f7-8e01-9ece53eeceea.png">

**Comment by aleksa-krolls** [comment]
@lakhassane There are no docs, but I've discussed this with Quoin... and I tested myself using `PATCH`. 
See my original issue for more (including the payload to send in the HTTP request body)... but this def is the method to use.

**Comment by aleksa-krolls** [comment]
@lakhassane so long as docs are added for these 2 new Primero helpers, OK to close from my side. Unless there's another step to publish them on platform?
