### ISSUE TITLE
Remove `.` from after a JSON log?

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/language-primero#35]
This `.` mark feels out of place when I see it at the end of a blob of JSON. Thoughts @lakhassane ? 

https://github.com/OpenFn/language-primero/blob/f6e6445dda6e80aa76c44b33dad347d25d9bb705/src/Adaptor.js#L196

**Comment by lakhassane** [comment]
Hm not that weird to me but again I might not fully grasp the implication. Probably a typo?

**Comment by github4maninder** [comment]
Kindly assign it to me. I would like to resolve it. thanks

**Comment by github4maninder** [comment]
I have removed the typo and opened a pull request. thanks

**Comment by github4maninder** [comment]
Hi, let me know if the issue is fixed or if i need to make any other changes?
