### ISSUE TITLE
Ensure that expandReferences is used across adaptor

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/language-primero#37]
Right now, `getCases(query, callback)` doesn't `expandReferences` for that query. Imagine that you're using a cursor to fetch cases since the last time you ran the query. You'd want to use an `fn` block (or something like it) to set up state before using `getCases` and then you'd expect the query to be reevaluated if it was passed a function:

```js
fn(state => { ...state, myCursor: '2021-02-15' });

getCases({
  sex: state => state.data.genderFilter, // like this, or...
  last_updated_at: state => `${state.myCursor}..`
});
```

But I don't think passing a function to query works.

**Comment by lakhassane** [comment]
- [ ] getCases
- [ ] createCase
- [ ] updateCase
- [ ] upsertCase
- [ ] getReferrals
- [ ] createReferrals
- [ ] updateReferrals
