### ISSUE TITLE
Primero V2 adaptor

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/language-primero#7]
## Background 
Primero has 2 main versions actively used across implementations worldwide. Some countries like Cambodia will continue to use the older v1, but all new Primero implementations going forward will use v2 of the software, which is very similar but has some feature upgrades and a slightly different API. OFG will first use the V2 adaptor for the upcoming Thailand implementation (we expect to have OpenFn specs finalized only in December). 

## Request
Based on known Thailand requirements to-date, please develop a v2 of the Primero adaptor that can perform the following operations...
1. Get `cases` (ideally to send in bulk to an external MOH system on a scheduled basis)
2. Upsert `cases` (as in the v1 adaptor, we may need to first GET cases before we can create/update. We also anticipate that there might be [multiple externalIds](https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/f2-j2-upsertCasesToPrimero.js#L538) to use in upserts)
3. Upsert `referrals` (again, we may need to GET and then create/update)
4. Downstream other helpful operations might include the ability to upsert `agencies` and upsert `locations`

When finished, please make sure the language-packs are updated with job snippet examples. If you have any questions regarding the API behavior, you can email pavel.nabutovsky@quoininc.com and copy me. 

## Inputs
See LP `Primero Staging Thailand` for the test Primero Thailand v2 instance you can use. 

See this [`sampleCaseToPrimero.json`](https://github.com/OpenFn/unicef-thailand/blob/master/sample_data/sampleCaseToPrimero.json) for a sample case upload payload to use. 

Primero v2 API docs: https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api/v2/docs
1. Authentication: https://github.com/primeroIMS/primero/blob/development_v2/app/controllers/api/v2/docs/tokens/post.md
_From Pavel: `POST /api/v2/tokens` issues a JWT token that you can use for subsequent requests... tokens last for 60 minutes, but you can reissue a token by doing a POST to that url with an unexpired token without a username/password_
2. Cases: https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api/v2/docs/cases
3. Referrals: https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api/v2/docs/referrals

**Comment by taylordowns2000** [comment]
@aleksa-krolls , we've broken this out into its constituent pieces and @lakhassane has delivered #9 and #10 . He's got a question (needs more example data) on `upsertReferrals` (#11) and I would like you to prioritize these new features `upsertAgencies` and `upsertLocations` (#12 and #13) individually.

It feels like we should deliver #11 and then build and release `v2.0.0` so you can work with it on OpenFn.org. Then, `v2.1.0` can include these other new features. Thoughts? Is that the right move?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Yes, that's the right move...we don't know enough yet about v2 until we get into the Thailand implementation, so I can't share more at this time on #11, #12, and #13. So feel free to close this issue if no further action and I can bump the other ones later if we learn more.

**Comment by taylordowns2000** [comment]
Understood. Removing these extra features from the initial v2.0!

**Comment by aleksa-krolls** [comment]
Moving to those to ice box then, thanks

**Comment by aleksa-krolls** [comment]
@lakhassane @taylordowns2000 docs need to be part of every LP change (see my request and make sure we update the [`README`](https://github.com/OpenFn/language-primero#language-primero--)). I want to try to push us to get into this habit because without docs, it's hard to communicate to the client what we've delivered for adaptors... also we should record job snippets while things are fresh and we don't lose context. So I'm going to move this to Backlog... but feel free to make your own separate issues.
