### ISSUE TITLE
getCases v2

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/language-primero#9]

**Comment by aleksa-krolls** [comment]
This `getCases(...)` function does not work when I try to filter by an id. 

I've written the following job expression to try to fetch [this case](https://demo-care-thai-kids.primero.org/v2/cases/3e5a1131-084f-4186-8c06-44ecceab84a5) from the `Primero Staging Thailand` system (see LP). It returns `0` cases when I _know_ this case exists. 

```
getCases({
   remote: true,
    case_id:'a62401e8-d5c9-46e5-894f-a7b786bb0'
   //id: 3e5a1131-084f-4186-8c06-44ecceab84a5 //also tried fetching using record id
 },  state => {
    console.log(`Primero cases: ${JSON.stringify(state.data)}`);
    return { ...state, data: {}, references: [] }
  })
```
If I remove all ids from this expression to remove all filters and then run `getCases(...)`, the case with `"id": "3e5a1131-084f-4186-8c06-44ecceab84a5"` _does_ show up in the response that returns a total of ~20 cases.

**Comment by lakhassane** [comment]
@aleksa-krolls up in here I thing the `case_id` is incomplete. There is a missing `105` at the end.

Also this version of primero don't see to query with `id`. I retry the same expression with the correct `case_id` and it's working.

```js
getCases(
  {
    remote: true,
    case_id: 'a62401e8-d5c9-46e5-894f-a7b786bb0105',
    // id: "3e5a1131-084f-4186-8c06-44ecceab84a5" //also tried fetching using record id
  },
  state => {
    console.log(`Primero cases: ${JSON.stringify(state.data)}`);
    return { ...state, data: {}, references: []  };
  }
);

```
